### get root
GET http://localhost:3000

### get all cats
GET http://localhost:3000/cats
Content-Type: application/json
{
    "coba": "ok"
}

### create cat
POST http://localhost:3000/cats
Content-Type: application/json
{
    "id": 4,
    "nama": "curut",
    "umur": 3
}

### get cat
GET http://localhost:3000/cats/1

### update cat
PUT http://localhost:3000/cats/1
Content-Type: application/json
{
    "nama": "updated",
    "umur": 5
}

### delete cat
DELETE http://localhost:3000/cats/1
